### ISSUE TITLE
Realm Roadmap

### ISSUE THREAD

**Issue by thehowl** [gnolang/gnochess#2]
## Engine

- [x] En passant
- [x] Proper Castling checks
- [x] Check for checkmate
- [x] Check for stalemate
- [x] 50/75-move rule
- [x] 3/5-fold repetition
- [x] Insufficient material

### Engine testing

Re-adapting the ones from [notnil/chess](https://github.com/notnil/chess)

- [x] `TestCheckmate` / FromFEN
- [x] `TestStalemate`
- [x] `TestInvalidStalemate`
- [x] `TestThreeFoldRepetition`
- [x] `TestInvalidThreeFoldRepetition`
- [x] `TestFiveFoldRepetition`
- [x] `TestFiftyMoveRule`
- [x] `TestInvalidFiftyMoveRule`
- [x] `TestSeventyFiveMoveRule`
- [x] `TestInsufficientMaterial`
- [x] `TestSufficientMaterial`
- [x] `TestInitialNumOfValidMoves`
- [x] `TestValidMoves`
- [x] `TestInvalidMoves`
- [x] `TestPositionUpdates`
- [x] `TestPerfResults`

## Realm MVP features

- [x] `discovery.gno` 
  - [x] listing open games
  - [x] listing past games
  - [x] listing games by user involvement
  - [x] showing a player's Wins/Losses/Ties
  - [x] showing a leaderboard of players ranked by `wins-losses+ties/2`
- [x] `MakeMove` endgame conditions
- [x] `Forfeit` / `Draw` (one-party)

## Full Game Features

- [x] Draw by Agreement
- [x] Time Control
  - [x] modify API for `NewGame`
  - [x] general time allocation logic
  - [x] abort games (no response from other player within 30s)
  - [x] auto-timeout logic on MakeMove, reject if timed out on Draw/DrawOffer/Resign, `ClaimTimeout`
- [x] Glicko2 rating _(to be expanded...)_. [lila source](https://github.com/lichess-org/lila/tree/master/modules/rating/src/main/glicko2)
- [x] Matchmaking _(to be expanded...)_
- [x] Leaderboard pagination and distinction between Blitz and Rapid

## Event Features

- [ ] Generate event user registration tokens
- [x] Faucet (integrating with tokens ...)
- [ ] Player Registration (from a token, register with name/username/gh handle/email...)
- [x] Player Profile _(to be expanded...)_
